Skip upgrading to setuptools 36.2.1
During uninstall 36.2.0, the following exception raised for
setuptools:

Change-Id: I77fbac0da45480fce85ee8e9db1fc097a9fa5db9
AttributeError: Distribution instance has no attribute 'install_requires'