Restrict oslo.config version <6.6.0
After updating to 6.6.0:

  File "/home/jenkins/workspace/workspace/cookied-cicd-k8s-calico/tcp_tests/managers/envmanager_devops.py", line 203, in create_snapshot
    settings_oslo.save_config(self.__config, name, self.__env.name)
  File "/home/jenkins/workspace/workspace/cookied-cicd-k8s-calico/tcp_tests/settings_oslo.py", line 586, in save_config
    formatter = generator._OptFormatter(output_file=output_file)
TypeError: __init__() takes at least 2 arguments (2 given)

Change-Id: Ifd91dead4a3d50afdb5e77c3c96bea86d53ecc68