Restrict salt-pepper package to version <=0.5.3
After updating to the version 0.5.4 the following error
raised:

Traceback (most recent call last):
  File "tcp_tests/fixtures/salt_fixtures.py", line 74, in salt_deployed
    salt_nodes = salt_actions.get_ssh_data()
  File "tcp_tests/managers/saltmanager.py", line 180, in get_ssh_data
    hosts = self.local('*', 'grains.item', ['host', 'ipv4'])
  File "tcp_tests/managers/saltmanager.py", line 108, in local
    return self.api.local(tgt, fun, args, kwargs, expr_form='compound')
  File "tcp_tests/managers/saltmanager.py", line 104, in api
    self.__session_start = login()
  File "tcp_tests/managers/saltmanager.py", line 88, in login
    eauth='pam')
  File "site-packages/pepper/libpepper.py", line 455, in login
    'eauth'
  File "site-packages/pepper/libpepper.py", line 456, in <genexpr>
    ) if locals()[key] is not None
KeyError: 'username'

Change-Id: Id03ffcf3c9933aa76c47d640620bbf27c48ecc96